apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pyhttp
  template:
    metadata:
      labels:
        app: pyhttp
    spec:
      containers:
        - name: python
          image: python:3.11-slim
          command: ["python", "-m", "http.server"]
          ports:
            - containerPort: 8000