apiVersion: v1
kind: Pod
metadata:
  name: liveness-demo
spec:
  containers:
  - name: app
    image: python:3.9-slim
    ports:
    - containerPort: 8080
    command: ["/bin/sh", "-c"]
    args:
      - |
        pip install flask && \
        printf "from flask import Flask, request\nimport os\n\napp = Flask(__name__)\n\n@app.route('/healthz')\ndef healthz():\n    if os.path.exists('/tmp/healthy'):\n        return 'OK', 200\n    else:\n        return 'FAIL', 500\n\napp.run(host='0.0.0.0', port=8080)\n" > /app.py && \
        touch /tmp/healthy && \
        python3 /app.py
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 10
      periodSeconds: 5
      failureThreshold: 1
