apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-db-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-db-app
  template:
    metadata:
      labels:
        app: web-db-app
    spec:
      containers:
        - name: web-db-app
          image: web-db-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASSWORD