apiVersion: apps/v1
kind: Deployment
metadata:
  name: recreate-demo
spec:
  replicas: 5
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: recreate-demo
  template:
    metadata:
      labels:
        app: recreate-demo
    spec:
      containers:
      - name: flask-app
        image: python:3.9-slim
        ports:
        - containerPort: 8080
        command: ["/bin/sh", "-c"]
        args:
          - |
            pip install flask && \
            printf "from flask import Flask\nimport time\n\napp = Flask(__name__)\n\n@app.route('/ready')\ndef ready():\n    return 'OK', 200\n\ntime.sleep(10)\napp.run(host='0.0.0.0', port=8080)\n" > /app.py && \
            python3 /app.py
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 5
