apiVersion: v1
kind: Pod
metadata:
  name: app-pv-pod
spec:
  containers:
    - name: app
      image: busybox
      command: ["sh", "-c", "while true; do echo 'Hello from PV' >> /data/hello.txt; sleep 10; done"]
      volumeMounts:
        - name: my-storage
          mountPath: /data
  volumes:
    - name: my-storage
      persistentVolumeClaim:
        claimName: my-pvc
