apiVersion: v1
kind: Pod
metadata:
  name: startup-demo
spec:
  containers:
  - name: app
    image: python:3.9-slim
    ports:
    - containerPort: 8080
    command: ["/bin/sh", "-c"]
    args:
      - |
        pip install flask && \
        printf "from flask import Flask\nimport os\nimport time\n\napp = Flask(__name__)\n\n@app.route('/healthz')\ndef healthz():\n    if os.path.exists('/tmp/started'):\n        return 'OK', 200\n    else:\n        return 'Starting', 500\n\ntime.sleep(30)\nopen('/tmp/started', 'w').close()\napp.run(host='0.0.0.0', port=8080)\n" > /app.py && \
        python3 /app.py
    startupProbe:
      httpGet:
        path: /healthz
        port: 8080
      periodSeconds: 5
      failureThreshold: 10
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 0
      periodSeconds: 5
    readinessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 0
      periodSeconds: 5
