apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-db
  namespace: t1-kube
spec:
  serviceName: "mongo-db" # Referencia requerida, pero no se define el servicio por ahora
  replicas: 3
  selector:
    matchLabels:
      app: mongo-db
  template:
    metadata:
      labels:
        app: mongo-db
    spec:
      containers:
        - name: mongo-db
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi